org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=false
org.gradle.parallel=true

minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.21)
forge_version=47.4.21
forge_version_range=[47,)
loader_version_range=[47,)
mapping_channel=parchment
mapping_version=2023.09.03-1.20.1

jei_version=15.20.0.130
codechickenlib_version=4.4.0.516
dynamic_lights_version=1.20.1.2
dynamic_lights_file_id=4861183

mod_id=lightsabers
mod_name=Advanced Lightsabers
mod_license=LGPL-3.0-only
mod_version=1.0
mod_group_id=com.fiskmods.lightsabers
mod_authors=LirxOwO，Xiris177, sdjge, DrowningFish233
mod_description=Adds lightsabers and force powers.
